// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOhqFDnScFtjn5mOCVCTtHuj_Ybq4JaGk',
    appId: '1:1032711100689:web:302bbf4c7f1284059054b0',
    messagingSenderId: '1032711100689',
    projectId: 'spotify011111',
    authDomain: 'spotify011111.firebaseapp.com',
    storageBucket: 'spotify011111.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoGTr-YzOmNBvaMkelXZ5Cv3vXq0_cBnU',
    appId: '1:1032711100689:android:cc1b4e57e2d7f7d39054b0',
    messagingSenderId: '1032711100689',
    projectId: 'spotify011111',
    storageBucket: 'spotify011111.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiz4t3YI8tQh4WLUJU1smGEljV9kTLhUs',
    appId: '1:1032711100689:ios:fa5b9a461d62951f9054b0',
    messagingSenderId: '1032711100689',
    projectId: 'spotify011111',
    storageBucket: 'spotify011111.firebasestorage.app',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiz4t3YI8tQh4WLUJU1smGEljV9kTLhUs',
    appId: '1:1032711100689:ios:fa5b9a461d62951f9054b0',
    messagingSenderId: '1032711100689',
    projectId: 'spotify011111',
    storageBucket: 'spotify011111.firebasestorage.app',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOhqFDnScFtjn5mOCVCTtHuj_Ybq4JaGk',
    appId: '1:1032711100689:web:c96b221cc5fdfa419054b0',
    messagingSenderId: '1032711100689',
    projectId: 'spotify011111',
    authDomain: 'spotify011111.firebaseapp.com',
    storageBucket: 'spotify011111.firebasestorage.app',
  );
}
