// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2e8BqPwV3wZJnEpotlgwfoHmNPVS32z4',
    appId: '1:176667934485:web:5674b898a78a2f3008331c',
    messagingSenderId: '176667934485',
    projectId: 'gaming-94110',
    authDomain: 'gaming-94110.firebaseapp.com',
    storageBucket: 'gaming-94110.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0ldOkfxqrtsPPHsuoqSfvWqL3NYjp0rI',
    appId: '1:176667934485:android:0540d04b16a322de08331c',
    messagingSenderId: '176667934485',
    projectId: 'gaming-94110',
    storageBucket: 'gaming-94110.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6yozLRexp8A_CBS9KVl1d2YpT9hb3R7g',
    appId: '1:176667934485:ios:58e02d913cb8972b08331c',
    messagingSenderId: '176667934485',
    projectId: 'gaming-94110',
    storageBucket: 'gaming-94110.appspot.com',
    iosClientId:
        '176667934485-u4voo2dab0u618q5esmlf6b67dlnrik3.apps.googleusercontent.com',
    iosBundleId: 'com.spotify000000123',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6yozLRexp8A_CBS9KVl1d2YpT9hb3R7g',
    appId: '1:176667934485:ios:58e02d913cb8972b08331c',
    messagingSenderId: '176667934485',
    projectId: 'gaming-94110',
    storageBucket: 'gaming-94110.appspot.com',
    iosClientId:
        '176667934485-u4voo2dab0u618q5esmlf6b67dlnrik3.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS_X8tUxWT9vUrbfJFK2XuMdbBI6NNugo',
    appId: '1:176667934485:web:03bcb7c46d28f9ca08331c',
    messagingSenderId: '176667934485',
    projectId: 'gaming-94110',
    authDomain: 'gaming-94110.firebaseapp.com',
    storageBucket: 'gaming-94110.appspot.com',
  );
}
